name: Smart Build sing-box

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: reF1nd-testing
            tag: singbox-testing
            name: Testing
          - branch: reF1nd-stable
            tag: singbox-stable
            name: Stable
          - branch: reF1nd-oldstable
            tag: singbox-oldstable
            name: OldStable

    steps:
      - name: Check Updates
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=$(git ls-remote https://github.com/reF1nd/sing-box.git refs/heads/${{ matrix.branch }} | awk '{ print $1 }')
          UPSTREAM=${SHA:0:7}
          
          if [ -z "$UPSTREAM" ]; then exit 1; fi
          
          LOCAL=$(gh release view ${{ matrix.tag }} --repo ${{ github.repository }} --json body --jq .body 2>/dev/null | grep -oP '```
